lecture.03の課題について
Mizuho-git/raicetech-lecture pull request #1
Opened 2023-03-27 14:17 UTC by Mizuho-git

ご確認よろしくお願いします。

2023-03-30 14:08 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応おねがいします！

2023-03-30 14:08 UTC, MasatoshiMizumoto commented on lecture03.md
画像はmarkdownと同じ方法でpushすれば相対Pathで書いて表示できるので、その方法に変更ください！
PR維持したままできるので、よろしくおねがいします！

2023-03-30 16:05 UTC, Mizuho-git commented on lecture03.md
調べながらやったのですが、やり方としてはこちらで合っていますでしょうか。。？

2023-03-30 16:13 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご確認いただきたいです！

2023-04-01 14:57 UTC, Mizuho-git commented on lecture03.md
> +![アプリの起動確認](https://user-images.githubusercontent.com/101118195/227972378-249507c3-9b92-4c30-a31d-655171c6f86a.png)
お疲れ様です。
リポジトリ内にimageディレクトリを作成し、その中に画像を配置しそこまでのパスを相対パスとして書き換えました。
認識としてはこちらで合っていますでしょうか？？
お手隙の際にご確認よろしくお願いいたします。

2023-04-01 15:03 UTC, Mizuho-git commented on README.md
lecture.03の方にREADMEを作成し直しました。
ご指摘ありがとうございます。

2023-04-01 15:09 UTC, MasatoshiMizumoto approved these changes
LGTM!

2023-04-25 06:10 UTC, closed without merging