第5回目課題を提出します。
Mizuho-git/raicetech-lecture pull request #5
Opened 2023-04-28 05:36 UTC by Mizuho-git

第5回目課題を提出します。ご確認よろしくお願いします。

2023-04-28 08:41 UTC, MasatoshiMizumoto requested changes
mdファイルどこ行きましたかね？？？

2023-04-28 08:42 UTC, MasatoshiMizumoto commented on images05/aws_kouseizu.drawio.png
S3EndpointはVPC Endpointのひとつなので、他のアイコンを探してみてください！

2023-04-28 09:44 UTC, Mizuho-git commented on images05/aws_kouseizu.drawio.png
課題提出用のlecture05.mdファイルはlecture05ブランチ配下に置いてあります。
構成図のアイコンを修正しました。

ご確認よろしくお願いします。

2023-04-29 10:20 UTC, MasatoshiMizumoto commented on lecture03.md
このファイルもこのままだと消えますね！！

2023-04-29 10:21 UTC, MasatoshiMizumoto requested changes
lecture03消えてしまうのでご確認ください！

2023-04-30 05:16 UTC, MasatoshiMizumoto approved these changes
LGTM!

2023-05-01 05:14 UTC, merged